### ISSUE TITLE
ncurses-6.2-he6710b0_1 appears to be corrupted in Ubuntu 20.04 of WSL

### ISSUE THREAD

**Issue by HuaZou** [oharch/conda-recipes#2]
When I used conda to install qiime2 *conda create -n qiime2-2020.8  qiime2=2020.8.0 --yes*, it reported this error:

```markdown
Preparing transaction: done
Verifying transaction: \
SafetyError: The package for ncurses located at /mnt/d/ubuntu/anaconda3/pkgs/ncurses-6.2-he6710b0_1
appears to be corrupted. The path 'share/terminfo/E/Eterm'
has an incorrect size.
  reported size: 2224 bytes
  actual size: 842 bytes
```
At first, I uninstalled ncurses pakckage and reinstalled it again, but the same bug couldn't be solved. After that, I reinstalled the whole ananconda3  envirnment, unfortunately, the problem still appeared.  So someone can help me to solve this bug? 

My anaconda information as follows:
```bash
active environment : base
    active env location : /mnt/d/ubuntu/anaconda3
            shell level : 1
       user config file : /home/hua/.condarc
 populated config files : /home/hua/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /mnt/d/ubuntu/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/qiime2/noarch
          package cache : /mnt/d/ubuntu/anaconda3/pkgs
                          /home/hua/.conda/pkgs
       envs directories : /mnt/d/ubuntu/anaconda3/envs
                          /home/hua/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.4.0-19041-Microsoft ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by alienzj** [comment]
Solved ?

**Comment by HuaZou** [comment]
Nope, this bug would appear when I create a new envirnment.  I have no idea to fix it. Could you give me some adivce?

**Comment by alienzj** [comment]
```
active environment : None
             shell level : 0
        user config file : /home/zhujie/.condarc
  populated config files : /home/zhujie/.condarc
           conda version : 4.8.4
     conda-build version : 3.19.2
          python version : 3.7.8.final.0
        virtual packages : __glibc=2.17
        base environment : /ldfssz1/ST_META/share/User/zhujie/.conda/envs/bioenv3.7  (writable)
            channel URLs : https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/biobakery/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/biobakery/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/qiime2/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/qiime2/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/ohmeta/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/cloud/ohmeta/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/noarch
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
                           https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
         package cache : /ldfssz1/ST_META/share/User/zhujie/.conda/pkgs
        envs directories : /ldfssz1/ST_META/share/User/zhujie/.conda/envs
                           /ldfssz1/ST_META/share/User/zhujie/.conda/envs/bioenv3.7/envs
                           /home/zhujie/.conda/envs
                platform : linux-64
              user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.8 Linux/2.6.32-696.30.1.el6.x86_64 centos/6.9 glibc/2.17
                 UID:GID : 666715:2782
              netrc file : None
```

**Comment by alienzj** [comment]
Please add more channel to your `~/.condarc`

**Comment by alienzj** [comment]
Try this method: https://docs.qiime2.org/2020.8/install/native/#install-qiime-2-within-a-conda-environment

When you download qiime2-2020.8-py36-linux-conda.yml, edit it and change content:
`qiime2/label/r2020.8`  => `qiime2`
then install.

**Comment by HuaZou** [comment]
Thanks for your kind help. Actually, I have done this before installing the qiime2-2020.8 version, but  the bug still haapped. In the same time, my .condarc have added the tsinghua position.  In my view, I think this bug maybe related to the OS (my platform is Unbuntu 20.04 in WSL2 of the window 10) because I haven't met the same bug on the cluster server whose OS is centos 8. Anyway, thanks a lot again.
```bash
channels:
  - defaults
  - conda-forge
  - bioconda
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/qiime2/
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  qiime2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

> Try this method: https://docs.qiime2.org/2020.8/install/native/#install-qiime-2-within-a-conda-environment
> 
> When you download `qiime2-2020.8-py36-linux-conda.yml`, edit it and change content:
> `qiime2/label/r2020.8` => `qiime2`
> then install.

**Comment by alienzj** [comment]
The order of channels is very important:
```
- channels:
   - conda-forge
   - bioconda
   - defaults
```

And try change the position of url related "cloud"  to custom_channels.

**Comment by alienzj** [comment]
```
channels:
    - conda-forge
    - bioconda
    - biobakery
    - qiime2
    - ohmeta
    #  - alienzj
    #  - pytorch
    #  - knights-lab
    #  - vanhemertjohn
    - defaults

show_channel_urls: true
#report_errors: true

#channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
channel_alias: https://mirrors.bfsu.edu.cn/anaconda

default_channels:
    #  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    #  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    #  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
    - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
    - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
    - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r

custom_channels:
    #  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    #  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    #  biobakery: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    #  qiime2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    #  ohmeta: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    #  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
    conda-forge: https://mirrors.bfsu.edu.cn/anaconda/cloud
    bioconda: https://mirrors.bfsu.edu.cn/anaconda/cloud
    biobakery: https://mirrors.bfsu.edu.cn/anaconda/cloud
    qiime2: https://mirrors.bfsu.edu.cn/anaconda/cloud
    ohmeta: https://mirrors.bfsu.edu.cn/anaconda/cloud
    #  pytorch: https://mirrors.bfsu.edu.cn/anaconda/cloud

    knights-lab: https://conda.anaconda.org
    alienzj: https://conda.anaconda.org
```
